### Class Task 1



1. Matrix A = (2,3) matrix (2 rows and 3 columns)
Matrix B = (3,2) matrix (3 rows and 2 columns)




2.  a). Yes, the matrices can be multiplied since matrix A has 3 columns and matrix B has 3 rows. 

    b).  Yes , the multipliation can be done both ways since even when interchanged the matrices rows and columns is equal to each other. 2 columns for matrix A = 2 rows for matrix B.
    Therefore , Matrix [AB = BA]




In [5]:
import numpy as np

matrix_A = np.array([[2,-1,3],[0,4,1]])
matrix_A


array([[ 2, -1,  3],
       [ 0,  4,  1]])

In [6]:
matrix_B = np.array([[[1,2],[-2,0],[5,-3]]])
matrix_B

array([[[ 1,  2],
        [-2,  0],
        [ 5, -3]]])

In [7]:
Matrix_C = matrix_A @ matrix_B
Matrix_C

array([[[19, -5],
        [-3, -3]]])

Confirming that matrix B can be multiplied with matrix A

In [8]:
matrix_D = matrix_B @ matrix_A
matrix_D

array([[[  2,   7,   5],
        [ -4,   2,  -6],
        [ 10, -17,  12]]])