### Student Performance Analysis With Linear Algebra

### 1 . Analysis 2. Exercises

In [96]:
import numpy as np

### 1. Analysis

 #### 3.1 Representing Data as a matrix

$$
Scores = \begin{bmatrix}
80 & 70 & 90 \\
60 & 85 & 75 \\
95 & 88 & 92 \\
70 & 60 & 65 
\end{bmatrix}





In [97]:
scores = np.array([[80,70,90],[60,85,75],[95,88,92],[70,60,65]])
student1_scores = np.array([80,70,90])
student2_scores = np.array([60,85,75])
student3_scores = np.array([95,88,92])
student4_scores = np.array([70,60,65])
print(scores)

[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


#### 3.2 Total Scores per Student (Vector Addition)

student 1 = [80 + 70 + 90] = 240
<br>

student 2 = [60 + 85 + 75] = 220
<br>

student 3 = [95 + 88 + 92] = 275
<br>

student 4 = [70 + 60 + 65] = 195

In [98]:
student1_scores.sum()
print(f"Student 1 total score is {student1_scores.sum()}")

Student 1 total score is 240


In [99]:
student2_scores.sum()
print(f"Student 2 total score is {student2_scores.sum()}")

Student 2 total score is 220


In [100]:
student3_scores.sum()
print(f"Student 3 total score is {student3_scores.sum()}")

Student 3 total score is 275


In [101]:
student4_scores.sum()
print(f"Student 4 total score is {student1_scores.sum()}")

Student 4 total score is 240


#### 3.3 Aplying Weights (Scalar Multiplication)
Maths_scalar = 2
<br>
English_scalar = 1.5
<br>
Science_scalar = 1
<br>

Maths_weight = 2(Math_scores)

$$
Maths Weight = \begin{bmatrix}
160 \\
120 \\
190 \\
140 \\
\end{bmatrix}


In [102]:
scalar_weight = [2,1.5,1]
Maths_weight = scalar_weight[0] * scores[:,0]
print("Mathematics Weight :",Maths_weight)

Mathematics Weight : [160 120 190 140]



English_weight = 2(English_scores)

$$
English Weight = \begin{bmatrix}
105 \\
127.5 \\
132 \\
90 \\
\end{bmatrix}

In [103]:
English_weight = scalar_weight[1] * scores[:,1]
print("English Language Weight :",English_weight)

English Language Weight : [105.  127.5 132.   90. ]



Science_weight = 1(Science_scores)

$$
Science Weight = \begin{bmatrix}
90 \\
75 \\
92 \\
65 \\
\end{bmatrix}

In [104]:
Science_weight = scalar_weight[2] * scores[:,2]
print("Science Weight :",Science_weight)

Science Weight : [90 75 92 65]


#### 3.4 Average Score per Subject (Matrix Operations)

Maths_Average = (80 + 60 + 95 + 70)/4 = 305/4 = 76.25
<br>

English_Average = (70 + 85 + 88 + 60)/4 = 303/4 = 75.75
<br>

Science_Average = (90 + 75 + 92 + 65) = 322/4 = 80.5

In [105]:
# Average Score per Students

Scores_per_subject = np.mean(scores,axis = 0)
scoress = ['Maths','English','Science']
b = 1
for scoress,st in zip(scoress,Scores_per_subject):
    print(f"Average {scoress} scores : {st}")
    b+=1

Average Maths scores : 76.25
Average English scores : 75.75
Average Science scores : 80.5


#### 3.5 Final Grades using Matrix Multiplication

weight_vector = [0.5 , 0.3 ,0.2]

Math_final_grades :
$$
0.5*Maths_Scores = \begin{bmatrix}
40 \\
30 \\
47.5 \\
35
\end{bmatrix}




In [106]:
# Math fnal grades 
scalar_math = 0.5
Math_final_grades = scalar_math * scores[:,0]
print(f"Mathematics Final grades : \n{Math_final_grades.reshape(4,1)}")

Mathematics Final grades : 
[[40. ]
 [30. ]
 [47.5]
 [35. ]]




English_final_grades :
$$
0.3*English_Scores = \begin{bmatrix}
21 \\
25.5 \\
26.4 \\
18
\end{bmatrix}


In [107]:
# English fnal grades 
scalar_english = 0.3
English_final_grades = scalar_english * scores[:,1]
print(f"English Final grades : \n{English_final_grades.reshape(4,1)}")

English Final grades : 
[[21. ]
 [25.5]
 [26.4]
 [18. ]]



Science_final_grades :
$$
0.2*Science_Scores = \begin{bmatrix}
18 \\
15 \\
18.4 \\
13
\end{bmatrix}


In [108]:
# Science fnal grades 
scalar_science = 0.2
Science_final_grades = scalar_science * scores[:,2]
print(f"Science Final grades : \n{Science_final_grades.reshape(4,1)}")

Science Final grades : 
[[18. ]
 [15. ]
 [18.4]
 [13. ]]


#### 3.6 Comparing Students (Vector Subtraction)
student1_Math_score = 80
<br>

student1_English_score = 70
<br>

Student1_scores = [80 + 70 + 90] = 240
<br>


student2_Math_score = 60
<br>

student2_English_score = 85
<br>

Student2_scores = [60 + 85 + 75] = 220
<br>


student1_Math_score - student2_Math_score = 80 - 60 = 20
<br>

#### Student1 performed better in Mathematics than student 2
<br>

student1_Eglish_score - student2_English_score = 70 - 85 = -15
<br>

#### Student2 performed better in English Language than student 1
<br>


student1_Science_score - student2_Science_score = 90 - 75 = 15
<br>

#### Student1 performed better in Science than student 2
<br>


Overall :
<br>

Student1_scores = [80 + 70 + 90] = 240  -   Student2_scores = [60 + 85 + 75] = 220
<br>

### Student 1 performed better overall than Student 2

In [109]:
Math_compared = scores[0,0] - scores[1,0]
print(f"Student 1 performed better than Student 2 in Mathematics with a difference of {Math_compared}")

Student 1 performed better than Student 2 in Mathematics with a difference of 20


In [110]:
English_compared = scores[0,1] - scores[1,1]
print(f"Student 2 performed better than Student 1 in Engish with a difference of 15")


Student 2 performed better than Student 1 in Engish with a difference of 15


In [111]:
Science_compared = scores[0,2] - scores[1,2]
print(f"Student 1 performed better than Student 2 in Science with a difference of {Science_compared}")

Student 1 performed better than Student 2 in Science with a difference of 15


In [112]:
studen1_overall_scores = np.sum(scores[0])

student2_overall_scores = np.sum(scores[1])

student_overall_compared = studen1_overall_scores - student2_overall_scores

print(f"Student 1 performed better overall than Student 2 with an overall difference of {student_overall_compared}")

Student 1 performed better overall than Student 2 with an overall difference of 20


### Add-on Exercises

1. 
$$
Scores = \begin{bmatrix}
80 & 70 & 90 & 50 \\
60 & 85 & 75 & 60 \\
95 & 88 & 92 & 70 \\
70 & 60 & 65 & 80 \\
70 & 55 & 75 & 60 


\end{bmatrix}

In [113]:
scores = np.array([[80,70,90,50],[60,85,75,60],[95,88,92,70],[70,60,65,80],[70,55,75,60]])
student1_scores = np.array([80,70,90,50])
student2_scores = np.array([60,85,75,60])
student3_scores = np.array([95,88,92,70])
student4_scores = np.array([70,60,65,80])
student5_scores = np.array([70,55,75,60])
print(scores)

[[80 70 90 50]
 [60 85 75 60]
 [95 88 92 70]
 [70 60 65 80]
 [70 55 75 60]]


#### 3.2 Total Scores per Student (Vector Addition)

student 1 = [80 + 70 + 90 + 50] = 290
<br>

student 2 = [60 + 85 + 75 + 60] = 280
<br>

student 3 = [95 + 88 + 92 + 70] = 345
<br>

student 4 = [70 + 60 + 65 + 80] = 275
<br>

student 5 = [70 + 55 + 75 + 60] = 260

In [114]:
student1_scores.sum()
print(f"Student 1 total score is {student1_scores.sum()}")

Student 1 total score is 290


In [115]:
student2_scores.sum()
print(f"Student 2 total score is {student2_scores.sum()}")

Student 2 total score is 280


In [116]:
student3_scores.sum()
print(f"Student 3 total score is {student3_scores.sum()}")

Student 3 total score is 345


In [117]:
student4_scores.sum()
print(f"Student 4 total score is {student4_scores.sum()}")

Student 4 total score is 275


In [118]:
student5_scores.sum()
print(f"Student 4 total score is {student5_scores.sum()}")

Student 4 total score is 260


#### 3.4 Average Score per Subject (Matrix Operations)

Maths_Average = (80 + 60 + 95 + 70 + 70)/5 = 375/5 = 75
<br>

English_Average = (70 + 85 + 88 + 60 + 55)/5 = 358/5 = 71.6
<br>

Science_Average = (90 + 75 + 92 + 65 + 75)/5 = 397/5 = 79.4
<br>

Physics_Average = (50 + 60 + 70 + 80 + 60)/5 = 320/5 = 64

In [119]:
# Average Score per Students

Scores_per_subject = np.mean(scores,axis = 0)
scoress = ['Maths','English','Science','Physics']
b = 1
for scoress,st in zip(scoress,Scores_per_subject):
    print(f"Average {scoress} scores : {st}")
    b+=1

Average Maths scores : 75.0
Average English scores : 71.6
Average Science scores : 79.4
Average Physics scores : 64.0


#### 2. 
Maths_scalar = 3
<br>
English_scalar = 1
<br>
Science_scalar = 1
<br>

Maths_weight = 3(Math_scores)

$$
Maths Weight = \begin{bmatrix}
240 \\
180 \\
285 \\
210 \\
210
\end{bmatrix}





Scores with Maths Weight 



$$
Scores with MathsWeight = \begin{bmatrix}
240 & 70 & 90 & 50 \\
180 & 85 & 75 & 60 \\
285 & 88 & 92 & 70 \\
210 & 60 & 65 & 80 \\
210 & 55 & 75 & 60 


\end{bmatrix}

In [120]:
scalar_weight = [3,1,1]
Maths_weight = scalar_weight[0] * scores[:,0]
print("Mathematics Weight :",Maths_weight)

Mathematics Weight : [240 180 285 210 210]


In [121]:
new_scores = scores.copy()
new_scores

array([[80, 70, 90, 50],
       [60, 85, 75, 60],
       [95, 88, 92, 70],
       [70, 60, 65, 80],
       [70, 55, 75, 60]])

In [122]:
new_scores[:,0] = Maths_weight
print(f"The new scores : \n{new_scores}")

The new scores : 
[[240  70  90  50]
 [180  85  75  60]
 [285  88  92  70]
 [210  60  65  80]
 [210  55  75  60]]


#### 3. 
weight_vector = [0.4 , 0.2 ,0.3,0.1]

Math_final_grades :
$$
0.4*Maths_Scores = \begin{bmatrix}
32 \\
24 \\
38 \\
28 \\
28
\end{bmatrix}


In [124]:
# Math fnal grades 
scalar_math = 0.4
Math_final_grades = scalar_math * scores[:,0]
print(f"Mathematics Final grades : \n{Math_final_grades.reshape(5,1)}")

Mathematics Final grades : 
[[32.]
 [24.]
 [38.]
 [28.]
 [28.]]




English_final_grades :
$$
0.2*English_Scores = \begin{bmatrix}
14 \\
17 \\
17.6 \\
12 \\
11
\end{bmatrix}


In [125]:
# English fnal grades 
scalar_english = 0.2
English_final_grades = scalar_english * scores[:,1]
print(f"English Final grades : \n{English_final_grades.reshape(5,1)}")

English Final grades : 
[[14. ]
 [17. ]
 [17.6]
 [12. ]
 [11. ]]


In [135]:
# Science fnal grades 
scalar_science = 0.3
Science_final_grades = scalar_science * scores[:,2]
print(f"Science Final grades : \n{Science_final_grades.reshape(5,1)}")

Science Final grades : 
[[27. ]
 [22.5]
 [27.6]
 [19.5]
 [22.5]]


In [137]:
# Physics final grades 
scalar_physics = 0.1
physics_final_grades = scalar_physics * scores[:,3]
print(f"Physics Final grades : \n{physics_final_grades.reshape(5,1)}")

Physics Final grades : 
[[5.]
 [6.]
 [7.]
 [8.]
 [6.]]


In [ ]:
New_scoress = np.array([Math_final_grades,English_final_grades,Science_final_grades,physics_final_grades])
print()New_scoress

array([[32. , 24. , 38. , 28. , 28. ],
       [14. , 17. , 17.6, 12. , 11. ],
       [27. , 22.5, 27.6, 19.5, 22.5],
       [ 5. ,  6. ,  7. ,  8. ,  6. ]])